/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan1
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idalamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idnama = new javax.swing.JTextField();
        idkelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idhasilalamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idhasilnama = new javax.swing.JTextField();
        idhasilkelas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        oke = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*Formulir Siswa*");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 190, 50, 30);

        idalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idalamatActionPerformed(evt);
            }
        });
        getContentPane().add(idalamat);
        idalamat.setBounds(140, 190, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 90, 50, 30);

        idnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnamaActionPerformed(evt);
            }
        });
        getContentPane().add(idnama);
        idnama.setBounds(140, 90, 240, 30);

        idkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idkelasActionPerformed(evt);
            }
        });
        getContentPane().add(idkelas);
        idkelas.setBounds(140, 140, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 400, 50, 30);

        idhasilalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhasilalamatActionPerformed(evt);
            }
        });
        getContentPane().add(idhasilalamat);
        idhasilalamat.setBounds(140, 400, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 300, 50, 30);

        idhasilnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhasilnamaActionPerformed(evt);
            }
        });
        getContentPane().add(idhasilnama);
        idhasilnama.setBounds(140, 300, 240, 30);

        idhasilkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhasilkelasActionPerformed(evt);
            }
        });
        getContentPane().add(idhasilkelas);
        idhasilkelas.setBounds(140, 350, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 350, 50, 30);

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));
        jPanel1.setLayout(null);

        oke.setText("Oke");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, hapus, org.jdesktop.beansbinding.ObjectProperty.create(), oke, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeActionPerformed(evt);
            }
        });
        jPanel1.add(oke);
        oke.setBounds(150, 230, 60, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(220, 230, 63, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(300, 230, 70, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 270, 570, 220);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idalamatActionPerformed

    private void idnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnamaActionPerformed

    private void idkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idkelasActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        idnama.setText("");
        idkelas.setText("");
        idalamat.setText("");
        idhasilnama.setText("");
        idhasilkelas.setText("");
        idhasilalamat.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void idhasilalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhasilalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhasilalamatActionPerformed

    private void idhasilnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhasilnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhasilnamaActionPerformed

    private void idhasilkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhasilkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhasilkelasActionPerformed

    private void okeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeActionPerformed
        // TODO add your handling code here:
        String nama = idnama.getText();
        idhasilnama.setText(nama);
        String kelas = idkelas.getText();
        idhasilkelas.setText(kelas);
        String alamat = idalamat.getText();
        idhasilalamat.setText(alamat);
    }//GEN-LAST:event_okeActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new latihan1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idalamat;
    private javax.swing.JTextField idhasilalamat;
    private javax.swing.JTextField idhasilkelas;
    private javax.swing.JTextField idhasilnama;
    private javax.swing.JTextField idkelas;
    private javax.swing.JTextField idnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton keluar;
    private javax.swing.JButton oke;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
